# Generated by Django 4.1 on 2022-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=7, verbose_name='Telefono'),
        ),
    ]
